apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: k8s-llm-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vllm
  template:
    metadata:
      labels:
        name: vllm
    spec:
      runtimeClassName: nvidia
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        args:
        - --model
        - HuggingFaceTB/SmolLM2-135M-Instruct
        - --dtype
        - half
        - --gpu-memory-utilization
        - "0.25"
        resources:
          requests:
            memory: "12Gi"
            ephemeral-storage: "10Gi"
          limits:
            memory: "16Gi"
            ephemeral-storage: "20Gi"
        env:
        - name: VLLM_PORT
          value: "8000"
        volumeMounts:
          - mountPath: /root/.cache/huggingface
            name: hf-cache
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
      volumes:
      - name: hf-cache
        hostPath:
          path: /opt/huggingface-cache
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: k8s-llm-stack
spec:
  type: NodePort
  selector:
    name: vllm
  ports:
  - port: 8000
    nodePort: 30280
    name: http
    targetPort: 8000
    protocol: TCP 